swagger: "2.0"
info:
  description: "Crescendo App API Documentation"
  version: "1.0.0"
  title: "Crescendo API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "crescendo-app.herokuapp.com"
tags:
- name: "user"
  description: "Operaciones para usuarios"
schemes:
- "http"
paths:
  /users:
    post:
      tags:
      - "user"
      summary: "Crear un usuario"
      description: "Crea un usuario completo"
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Datos completos del usuario"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "User Successfully Created"
    get:
      tags:
      - "user"
      summary: "Listar Usuarios"
      description: "Obtener los usuarios en trending (10)"
      operationId: "listUsers"
      produces:
      - "application/json"
      responses:
        default:
          description: "Lista de usuarios"
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
      security:
      - secured:
        - "read"
  /users/{userId}:
    put:
      tags:
      - "user"
      summary: "Actualizar un usuario"
      description: "Actualizar a un usuario"
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "ID del usuario"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Datos completos del usuario"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "User Successfully Updated"
      security:
      - secured:
        - "write"
    delete:
      tags:
      - "user"
      summary: "Eliminar un usuario"
      description: "Elimina a un usuario"
      operationId: "deleteUser"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "ID del usuario"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Datos completos del usuario"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "User Successfully Deleted"
      security:
      - secured:
        - "write"
  /users/{userId}/artworks:
    get:
      tags:
      - "artworks"
      summary: "Listar Artworks"
      description: "Obtener los artworks por usuario"
      operationId: "listArtworks"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "ID del usuario"
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "Lista de artworks"
          schema:
            type: array
            items:
              $ref: "#/definitions/Artwork"
      security:
      - secured:
        - "read"
securityDefinitions:
  secured:
    type: "oauth2"
    authorizationUrl: "http://crescendo-app.herokuapp.com/authentication"
    flow: "implicit"
    scopes:
      write: "Edita, Actualiza, Elimina"
      read: "Lista"
definitions:
  User:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
      name:
        type: "string"
      age:
        type: "string"
      musicGenre:
        type: "string"
      musicRole:
        type: "string"
      location:
        type: "string"
      district:
        type: "string"
      avatar:
        type: "string"
    xml:
      name: "User"
  Artwork:
    type: "object"
    properties:
      videoURL:
        type: "string"
      title:
        type: "string"
      description:
        type: "string"
      thumbnal:
        type: "string"
    xml:
      name: "Artwork"
